pipeline {
    agent any
    stages {
        stage('Deliver for development') {
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Build') {
            parallel {
                stage('Test') {
                    steps {
                        echo "Tests running"
                        sleep 5
                    }
                 }

                 stage('Test FINAL') {
                     steps {
                         echo "Tests finished"
                         sleep 5
                     }
                  }
            }
        }
    }
}
