pipeline {
    agent any
    stages {
        stage('Deliver for development') {
            steps {
                echo "Starting"
            }
        }
        stage('Build') {
            parallel {
                stage('Test') {
                    steps {
                        echo "Tests running"
                        sleep 5
                    }
                 }

                 stage('Test FINAL') {
                     steps {
                         echo "Tests finished"
                         sleep 5
                     }
                  }
            }
        }
    }
}
